# Generated by Django 3.0 on 2020-02-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_goals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Goal',
        ),
    ]
