# Generated by Django 3.0 on 2020-02-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200215_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
